# General settings
[logging]
log_to_file = false # Enable/disable logging to a file (named <program>.log)
                    # Tip: on linux logging to the systemd journal is supported
stdout_debug = false # Enable debug logging level on stdout
file_debug = false # Enable debug logging level on the log file (if enabled)
                   # Note: not recommended, as debug log logs a lot of data
journal_debug = false # Enable debug logging level on the systemd journal (if enabled)

[mariadb]
user = "myuser" # Database username
password = "superSecretPassword" # Password to database user
host = "localhost" # IP address of the database host
port = 3306 # MariaDB port. This is 3306 unless you've manually changed it
database = "sondes" # Database name in MariaDB

[autorx]
port = 55673 # UDP port that autorx sends its payload summaries to


# Application specific settings
[archiver]
min_seconds_per_frame = 5 # Minimum seconds per frame to be stored to the DB. Note:
                          # The resolution is also limited by the setting `ozi_update_rate` in autorx,
                          # with the difference that AutoRX's cooldown is shared between all tracked sondes.
                          # So to actually reach the limit set here, make sure your autorx setting is low enough.
                          # Ideally, set it to 0, as floating point numbers will crash autorx on startup
min_frames = 60 # Minimum amount of frames that need to be received via UDP for the flight to not be discarded
                # Keep in mind that the default autorx setting it to only send a payload summary for every 5 received frames
rx_timeout = 300 # The time in seconds that needs to pass without a packet to stop reception of a specific sonde
                 # After reception for a sonde has been stopped due to timeout, archival will not continue, even if
                 # reception is regained to avoid long pauses between packets. Similar behaviour can still be configured
                 # if this option is set to a high value

[dashboard]
port = 55670 # Port for the dashboard

# Define graphs in dashboard
# Available graphs: week_sonde_count, sonde_types, week_burst_altitudes, week_frame_count (more to be added)
top_left_graph = "week_sonde_count"
top_right_graph = "sonde_types"
bottom_left_graph = "week_burst_altitudes"
bottom_right_graph = "week_frame_count"

[map]
port = 55671 # Port for the map
poi_max_results = 500 # Maxium number of results to stop showing the POI dots
                      # for first rx, last rx and burst.
                      # This doesn't really help the server, but takes a lot of load
                      # off of the client.



# Advanced settings
[maptiles]
url = "https://tile.openstreetmap.org/{z}/{x}/{y}.png" # Tile server URL.
                                                       # Check https://leafletjs.com/reference.html#tilelayer
                                                       # for detail about the format
attribution = "&copy; <a href='https://www.openstreetmap.org/copyright'>OpenStreetMap</a> contributors" # Attribution text
min_zoom = 0 # Minimum maptile zoom
max_zoom = 14 # Maximum maptile zoom

